INSERT INTO users (name, kind)
VALUES
    ('Alice Johnson', 1),    -- Regular
    ('Bob Smith', 2),        -- VIP
    ('Charlie Brown', 3),    -- Admin
    ('David Davis', 1),
    ('Eve Wilson', 2),
    ('Frank Miller', 3),
    ('Grace White', 1),
    ('Helen Turner', 2),
    ('Ian Harris', 3),
    ('Jack Anderson', 1),
    ('Katie Clark', 2),
    ('Liam Lee', 3),
    ('Mia Adams', 1),
    ('Noah Hall', 2),
    ('Olivia Lewis', 3),
    ('Sophia Scott', 1),
    ('William Wright', 2),
    ('Zoe Martin', 3),
    ('Oliver Rodriguez', 1),
    ('Luna Brown', 2),
    ('Leo Martinez', 3),
    ('Ava Wilson', 1),
    ('Ethan Taylor', 2),
    ('Olivia Moore', 3),
    ('Liam Jackson', 1),
    ('Emma Garcia', 2),
    ('Noah Martinez', 3),
    ('Isabella Johnson', 1),
    ('Lucas Davis', 2),
    ('Sophia Martinez', 3),
    ('Alexander Taylor', 1),
    ('Mia Garcia', 2),
    ('James Hall', 3),
    ('Emily Smith', 1),
    ('Benjamin Lewis', 2),
    ('Amelia Turner', 3),
    ('Elijah Adams', 1),
    ('Charlotte Hall', 2),
    ('Harper White', 3);
